// Copyright 2020 The Pigweed Authors
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: unit_test.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UnitTest_Run_FullMethodName = "/pw.unit_test.UnitTest/Run"
)

// UnitTestClient is the client API for UnitTest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UnitTestClient interface {
	// Runs registered unit tests, streaming back test events as they occur.
	Run(ctx context.Context, in *TestRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type unitTestClient struct {
	cc grpc.ClientConnInterface
}

func NewUnitTestClient(cc grpc.ClientConnInterface) UnitTestClient {
	return &unitTestClient{cc}
}

func (c *unitTestClient) Run(ctx context.Context, in *TestRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UnitTest_ServiceDesc.Streams[0], UnitTest_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TestRunRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UnitTest_RunClient = grpc.ServerStreamingClient[Event]

// UnitTestServer is the server API for UnitTest service.
// All implementations must embed UnimplementedUnitTestServer
// for forward compatibility.
type UnitTestServer interface {
	// Runs registered unit tests, streaming back test events as they occur.
	Run(*TestRunRequest, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedUnitTestServer()
}

// UnimplementedUnitTestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUnitTestServer struct{}

func (UnimplementedUnitTestServer) Run(*TestRunRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedUnitTestServer) mustEmbedUnimplementedUnitTestServer() {}
func (UnimplementedUnitTestServer) testEmbeddedByValue()                  {}

// UnsafeUnitTestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnitTestServer will
// result in compilation errors.
type UnsafeUnitTestServer interface {
	mustEmbedUnimplementedUnitTestServer()
}

func RegisterUnitTestServer(s grpc.ServiceRegistrar, srv UnitTestServer) {
	// If the following call pancis, it indicates UnimplementedUnitTestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UnitTest_ServiceDesc, srv)
}

func _UnitTest_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TestRunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UnitTestServer).Run(m, &grpc.GenericServerStream[TestRunRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UnitTest_RunServer = grpc.ServerStreamingServer[Event]

// UnitTest_ServiceDesc is the grpc.ServiceDesc for UnitTest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UnitTest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pw.unit_test.UnitTest",
	HandlerType: (*UnitTestServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _UnitTest_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "unit_test.proto",
}
